### ISSUE TITLE
Refactor Code.py

### ISSUE THREAD

**Issue by sak007** [sak007/MyDollarBot#2]

**Comment by sak007** [comment]
Deleted expense_record.json
Commit#

**Comment by sak007** [comment]
Fixed issue while saving/loading user_data
Commit# 475482d3d6cf47b60a492e46d46db663b98e52a0

**Comment by sak1997** [comment]
I tested this out - The edit functionality is still not working. Please look into this next.

**Comment by sak007** [comment]
Created a new issue for edit fix and assigned it to @zedunaid 
Issue Link: https://github.com/sak007/MyDollarBot/issues/3

**Comment by sak1997** [comment]
/delete is not working. Code stops running when we execute /delete from the telegram UI.

Stack trace from Python:
Athithya@DESKTOP-DM1OEHR MINGW64 ~/Desktop/Classes/CSC510 SE/ProjectPhase2/MyDollarBot/code (backlogs)
$ python code.py
2021-10-19 21:47:35,224 (__init__.py:638 MainThread) INFO - TeleBot: "Started polling."
ERROR:root:getUserHistory() missing 1 required positional argument: 'chat_id'
Traceback (most recent call last):
  File "C:\Users\Athithya\Desktop\Classes\CSC510 SE\ProjectPhase2\MyDollarBot\code\code.py", line 93, in main
    bot.polling(none_stop=True)
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 633, in polling
    self.__threaded_polling(non_stop, interval, timeout, long_polling_timeout, allowed_updates)
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 692, in __threaded_polling
    raise e
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 655, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\util.py", line 130, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\util.py", line 82, in run
    task(*args, **kwargs)
  File "C:\Users\Athithya\Desktop\Classes\CSC510 SE\ProjectPhase2\MyDollarBot\code\code.py", line 79, in command_delete
    delete.run(message, bot)
  File "C:\Users\Athithya\Desktop\Classes\CSC510 SE\ProjectPhase2\MyDollarBot\code\delete.py", line 9, in run
    user_list = helper.getUserHistory()
TypeError: getUserHistory() missing 1 required positional argument: 'chat_id'
2021-10-19 21:47:35.662534 name:Sri Athithya Kruth chat_id:1574038305
message: Food

2021-10-19 21:47:35.662534 name:Ashok chat_id:1222391743
message: Food

2021-10-19 21:47:39.670296 name:Sri Athithya Kruth chat_id:1574038305
message: hi

2021-10-19 21:47:42.250890 name:Sri Athithya Kruth chat_id:1574038305
message: /display

2021-10-19 21:47:51.893959 name:Sri Athithya Kruth chat_id:1574038305
message: /delete

Connection Timeout

**Comment by wizard-31** [comment]
We refactored the main file into multiple sub files and covered test cases for each functionality. 
Good to close the issue.
